In [4]:
import numpy as np

#Array using Numpy
#A 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)



[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) #1 row & 5 columns

array([[1, 2, 3, 4, 5]])

In [7]:
arr3 = np.array([[1,2,3,4,5]])
arr3.shape

(1, 5)

In [10]:
#2D Array
arr4 = np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7]])
print(arr4)
print(arr4.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]
(3, 5)


In [14]:
np.arange(0,9,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [15]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
# identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
#Attributes of Numpy 
arr = np.array([[1,2,3,4],[4,5,6,7]])

print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of dimensions:", arr.ndim)
print("Size(Number of elements):", arr.size)
print("Data type:", arr.dtype)
print("Item size(in bytes):", arr.itemsize)

Array:
 [[1 2 3 4]
 [4 5 6 7]]
Shape: (2, 4)
Number of dimensions: 2
Size(Number of elements): 8
Data type: int32
Item size(in bytes): 4


In [18]:
#Numpy Vectorized Operation
arr5 = np.array([1,2,3,4,5])
arr6 = np.array([10,20,30,40,50])

# Element wise addition
print("Addition", arr5+arr6)

# Element wise Subtraction
print("Subtraction:", arr5-arr6)

# Element wise Multiplication
print("Multiplication:", arr5*arr6)

# Element wise Division
print("Division", arr5/arr6)

Addition [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division [0.1 0.1 0.1 0.1 0.1]


In [20]:
#Universal Function
arr = np.array([2,3,4,5,6])
# Square root
print(np.sqrt(arr))

#Exponential
print(np.exp(arr))

#Sine
print(np.sin(arr))

#Natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [23]:
#Array Slicing & Indexing

arr = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [37]:
arr[0][0]

arr[:2,2:]

array([[3, 4],
       [6, 7]])

In [38]:
arr[1:,2:]

array([[ 6,  7],
       [ 9, 10]])

In [39]:
arr[1:,1:3]

array([[5, 6],
       [8, 9]])

In [41]:
#Modifying Array elements
arr[0,1] = 100
print(arr)

[[  1 100   3   4]
 [  4   5   6   7]
 [  7   8   9  10]]


In [42]:
arr[2:] = 100
print(arr)

[[  1 100   3   4]
 [  4   5   6   7]
 [100 100 100 100]]


In [43]:
#Statistical Concepts -> Normalization

data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [45]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

mean = np.mean(data)
print("Mean:", mean)

median = np.median(data)
print("Median",median)

std_dev = np.std(data)
print("Standard Deviation",std_dev)

variance = np.var(data)
print("Variance",variance)

Mean: 5.5
Median 5.5
Standard Deviation 2.8722813232690143
Variance 8.25


In [50]:
#Logical Operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])

In [48]:
data > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])